version: '3'
services:
  python-docker-example:
    build:
      context: .
      dockerfile: Dockerfile
    image: sccity/python-docker-example:test
    container_name: python-docker-example
    environment:
      - TZ=America/Denver
    restart: unless-stopped
    user: "1435:1435"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M